name: Gradle Smoke-Tests with Docker

on:
  push:

jobs:
  build:

    runs-on: [ self-hosted ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Run Smoke-Tests in a Docker Image
        run: ./gradlew smoke-tests:docker -PhubName=value -PclientName=value -PclientSecret=value -PbaseUrl=value
